"""Generate an AI-orientation map of the corpus.

`musubi map` emits a single markdown document that lets an agent (or a human)
grasp the whole knowledge base fast: every note, grouped, with a one-line
"what it's about" pulled from the note's own frontmatter `description` (or, when
absent, its strongest extracted concepts). This is the doc you READ ON DEMAND to
orient before drilling into a specific note with `musubi neighbors` / `qmd get`.

Stdlib only — no ML imports, so `musubi map` is as cheap as `stats`.
"""
from __future__ import annotations

import os
from collections import defaultdict
from typing import Any

from musubi.search import canonical_node_ids


def _aboutness(node: dict[str, Any]) -> str:
    desc = (node.get("description") or "").strip()
    if desc:
        return desc
    concepts = [c for c in node.get("concepts", []) if not c.startswith("h:")][:5]
    if concepts:
        return "concepts: " + ", ".join(concepts)
    return "(no description)"


def _group_key(node: dict[str, Any], by: str) -> list[str]:
    if by == "collection":
        return [node.get("collection", "?")]
    if by == "tag":
        raw = node.get("tags") or ""
        tags = [t.strip().strip("[]\"'") for t in str(raw).replace(",", " ").split()]
        return [t for t in tags if t] or ["(untagged)"]
    if by == "concept":
        concepts = [c for c in node.get("concepts", []) if not c.startswith("h:")]
        return concepts[:1] or ["(no concept)"]
    return [node.get("collection", "?")]


def _is_meta_doc(node: dict[str, Any]) -> bool:
    basename = os.path.basename(node.get("path") or "").lower()
    title = (node.get("title") or "").lower()
    return basename in {"kb_map.md", "kb-map.md", "log.md", "memory.md"} or "kb_map" in title


def generate_map(graph, by: str = "collection") -> str:
    """Return a markdown orientation map. `graph` is a musubi Graph."""
    groups: dict[str, list[tuple[str, dict[str, Any], int]]] = defaultdict(list)
    total = 0
    for nid, node in graph.id_to_node.items():
        total += 1
        deg = graph.deg(nid)
        for key in _group_key(node, by):
            groups[key].append((node.get("title", "?"), node, deg))

    lines: list[str] = []
    lines.append("# Knowledge-base map (musubi)")
    lines.append("")
    lines.append(
        f"> Auto-generated by `musubi map --by {by}` from {total} notes. "
        "Read this to grasp the whole corpus fast, then `musubi neighbors \"<slug>\"` "
        "or `qmd get <path>` to pull a specific note. Each line's summary is the note's "
        "frontmatter `description` (verbatim) or, when absent, its strongest concepts. "
        "❄ = isolated (no graph links); ⚠ = superseded."
    )
    lines.append("")

    for key in sorted(groups):
        items = sorted(groups[key], key=lambda x: x[0].lower())
        lines.append(f"## {key}  ({len(items)})")
        for title, node, deg in items:
            marks = ""
            if deg == 0:
                marks += " ❄"
            if node.get("confidence") == "superseded":
                marks += " ⚠"
            path = node.get("path", "")
            loc = f"  `{path}`" if path else ""
            lines.append(f"- **{title}**{marks} — {_aboutness(node)}{loc}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def generate_orient(
    graph,
    by: str = "collection",
    *,
    limit_per_group: int = 8,
    max_groups: int = 20,
) -> str:
    """Return a compact orientation map for agents.

    Unlike ``generate_map``, this intentionally samples representative,
    well-connected notes per group. It is safe to read at task start without
    flooding the context window.
    """
    groups: dict[str, list[tuple[str, dict[str, Any], int]]] = defaultdict(list)
    total = 0
    for nid in canonical_node_ids(graph):
        node = graph.id_to_node[nid]
        total += 1
        deg = graph.deg(nid)
        for key in _group_key(node, by):
            groups[key].append((node.get("title", "?"), node, deg))

    ordered_groups = sorted(groups.items(), key=lambda kv: (-len(kv[1]), kv[0].lower()))
    hidden_groups = max(0, len(ordered_groups) - max_groups)
    ordered_groups = ordered_groups[:max_groups]

    lines: list[str] = []
    lines.append("# Knowledge-base orientation (musubi)")
    lines.append("")
    lines.append(
        f"> Compact map from {total} canonical notes, grouped by `{by}`. "
        f"Shows up to {limit_per_group} representative notes per group. "
        "Use `musubi map` only when you need the exhaustive list."
    )
    lines.append("")

    for key, items in ordered_groups:
        sorted_items = sorted(
            items,
            key=lambda x: (_is_meta_doc(x[1]), -x[2], x[0].lower()),
        )
        hidden_items = max(0, len(sorted_items) - limit_per_group)
        lines.append(f"## {key}  ({len(sorted_items)})")
        for title, node, deg in sorted_items[:limit_per_group]:
            path = node.get("path", "")
            loc = f"  `{path}`" if path else ""
            lines.append(f"- **{title}** — {_aboutness(node)}{loc}  _(deg {deg})_")
        if hidden_items:
            lines.append(f"- ... +{hidden_items} more")
        lines.append("")

    if hidden_groups:
        lines.append(f"_... +{hidden_groups} more groups hidden. Increase `--max-groups` to show them._")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
